### ISSUE TITLE
Pagerank 

### ISSUE THREAD

**Issue by zizuo2050** [Renatochaz/mathematics_for_ML-Linear_algebra#1]
Can you just help me to explain

**Comment by Renatochaz** [comment]
Sure.
Please elaborate here where are you having difficulties

**Comment by zizuo2050** [comment]
Can you just explain pagerank i have just confused in formal of it

**Comment by Renatochaz** [comment]
I will try to explain here, but its kinda tricky:

Remember the exemple in the course, where we have a miniature internet with 4 webpages (A,B,C and D)

Page A has links to page B, C and D. Now, imagine that a person on page A has the same probability to click in any of these links. Whats is the probability to click on page B? Its 1/3, we only have 3 links. so we have the following vector for page A:

L_a = {0, 1/3, 1/3, 1/3}, where the first 0 is the chance to click in a link for page A (but this link doesn't exist, so its 0), and 1/3 for pages B, C and D.

Now, following the example of the course, we have the following matrix L (for all 4 webpages):

L = A    B    C    D
A  { 0   1/2  0    0
 B  1/3   0    0  1/2
 C  1/3   0    0  1/2
 D  1/3 1/2  1    0}

Note that this matrix represents the probability of ending in each of the web pages.

The first row represents the probability of ending in page A, because the only page that has links for page A is page B, and page B has two links, so its 1/2. The same logic applies to all of the matrix.

Now is when things gets tricky:

We want to know the probability of ending up at A if we are at B. 
But we need to know the probability of being at B! And we only know that if we know the rank of B, but to know the rank of B we would need to know the rank of A or D (because they have links to B). 

This means that this problem is self-referential (its a cycle), because the rank of the pages depends on the rank of all the others.

To deal with this problems we will know write an expression for the rank of page A only:

r_a = sum { L_{aj} r_j} (comments here doesn't allow mathematical expressions :( )

This equation is saying to me that the rank of page A (r_a) is the sum of the probability of ending up in page A from the matrix L multiplied by the rank of the page which is linking to page A.

Look at matrix L, the vector for page A is : {0 1/2 0 0}, this means that this expression is: r_a = 1/2 r_b (rank of page B). You can apply this same logic for the rank of all pages.

Now, remember about matrix notation? We can write a single notation for the rank of all webpages in this example (and for any number you want), just chaning the notation for r_a for r (all pages):

r  = Lr

this is saying that the vector r (the rank of all pages, in this case is 4 pages) is the multiplication of matrix L by the rank of r.
This is just the generalization of the expression: r_a = sum { L_{aj} r_j} (see matrix notation class of the course if you are having problems to understand this part)

Now, to solve this we are going to start somewhere. We will start by guessing the rank of all pages, and the "best" guess is just to say that all pages have the same rank, since we have 4 pages we will say that the rank of each page is 1/4.

Remember that the rank is the probability of ending in any page? Since in this discussion we are implying that you will end up in some of those webpages, the probability of ending in some of those 4 pages is 100%. This means that the probability of ending up in any page is 1/4 (because in this way, the probability of ending in some of those 4 pages is 100$)

now we have our vector r! But how can we go from this guess to the correct rank of each page?
We can do this by solving this problem iteratively (multiple times), so we will say that 

r(0) = {1/4 1/4 1/4 1/4} and we will update this chance by multiplying r(0) by our matrix L:

r(0) . L, this will give us an updated vector r (which we call r(1) )

Then we update r(1), this will give us r(2)

if you write this expression, just say that i = 0, and then you can say that:

r(i +1) = L . r(i)

If we do this multiple times, after sometime our updated r (i + 1) will stop changing, and when this happens our r( i + 1) will be equal to r (i).

Remember our expression?? : r(i+1) = L r(i)

If we think about this equality, we will see that r(i+1) will only be equal L r(i) if r(i) is an eigenvector with eigenvalue of 1!

Review the class of eigenvectors and you will se why this happens! :D

Hope this "informal" explanation helps, best of lucky!

**Comment by zizuo2050** [comment]
Thank you my bro it realy great help ❤😍
